version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - NODE_ENV=development
  backend:
    build: ./backend
    ports:
      - "5001:5000"  # ここを変更
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development